### PR TITLE
Add replicated log timeout.

### PR DESCRIPTION
**Pull request by urbanserj**
JIRA: https://jira.mesosphere.com/browse/DCOS_OSS-4575

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@urbanserj LGTM. Could you please add a test for it?

**Comment by urbanserj** [comment]
Hey @GoelDeepak,

I have been trying to add a unit test and found out that it will require pretty big code refactoring. Let me explain.

Please see how mesos tests this case [1] using mocked `Storage` [2] that is passed to `registrar` as a parameter [3]. To test the case in overlay module, we will have to make `Storage` or `State` parametrized. To be able to pass mocked class to `ManagerProcess`, we will have to move the class definitions from `master.cpp` to a new separate file as we did it with `agent.cpp` and `agent.hpp`. I started doing that code refactoring, but realized that it will take few days and tons of work which is out of scope for this issue.

[1] https://github.com/apache/mesos/blob/68ee08d/src/tests/registrar_tests.cpp#L1224-L1251
[2] https://github.com/apache/mesos/blob/68ee08d/src/tests/registrar_tests.cpp#L1214-L1221
[3] https://github.com/apache/mesos/blob/68ee08d/src/master/registrar.hpp#L92

**Comment by GoelDeepak** [comment]
> Hey @GoelDeepak,
> 
> I have been trying to add a unit test and found out that it will require pretty big code refactoring. Let me explain.
> 
> Please see how mesos tests this case [1] using mocked `Storage` [2] that is passed to `registrar` as a parameter [3]. To test the case in overlay module, we will have to make `Storage` or `State` parametrized. To be able to pass mocked class to `ManagerProcess`, we will have to move the class definitions from `master.cpp` to a new separate file as we did it with `agent.cpp` and `agent.hpp`. I started doing that code refactoring, but realized that it will take few days and tons of work which is out of scope for this issue.
> 
> [1] https://github.com/apache/mesos/blob/68ee08d/src/tests/registrar_tests.cpp#L1224-L1251
> [2] https://github.com/apache/mesos/blob/68ee08d/src/tests/registrar_tests.cpp#L1214-L1221
> [3] https://github.com/apache/mesos/blob/68ee08d/src/master/registrar.hpp#L92

I see. Let's capture this in a jira ticket to follow up in future.

**Comment by urbanserj** [comment]
@GoelDeepak Here is the ticket https://jira.mesosphere.com/browse/DCOS-47637

**Pull request merged**
