### PR TITLE
[1.12] Journald logrotate configuration file sealing

### PR DESCRIPTION
**Pull request by kaysoky**
## High-level description

What features does this change enable? What bugs does this change fix?

This is the 1.12 cherry-pick of #103.  These changes applied cleanly.

## Changelog automation

**Note**: This section is intended for robots. Titles supplied in this template will be used as CHANGELOG entries for this patch - consider diverting from the original JIRA subject to fit this purpose.

These JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands. One line per entry, no length limit.

[DCOS-47733](https://jira.mesosphere.com/browse/DCOS-47733) Disable modifications to container logger's custom logrotate options.

### CODE REVIEW

**Comment by kaysoky** [comment]
🤔 Looks like a weird git fetch error... I'll re-trigger the CI.
```
00:00:22.851 ~/workspace/mesos/modules/DCOS_OSS_Mesos_Modules-pr
00:00:22.892 ~/workspace/mesos/modules/DCOS_OSS_Mesos_Modules-pr/mesos ~/workspace/mesos/modules/DCOS_OSS_Mesos_Modules-pr
00:00:22.892 Checkout out Mesos: 5e234c8d8edc1bb73ba557f5774c609fa460c9e7
00:00:23.113 From https://gitbox.apache.org/repos/asf/mesos
00:00:23.113  * branch            HEAD       -> FETCH_HEAD
00:00:23.128 fatal: reference is not a tree: 5e234c8d8edc1bb73ba557f5774c609fa460c9e7
```

**Comment by tillt** [comment]
@reviewbot rebuild please

**Comment by tillt** [comment]
retest this please

**Comment by kaysoky** [comment]
Oops, this is failing because I didn't backport [MESOS-9564](https://issues.apache.org/jira/browse/MESOS-9564) to the 1.7.x branch.  The signature of the memfd create function was exposed in one of those commits.

**Comment by kaysoky** [comment]
retest this please

**Comment by kaysoky** [comment]
Ok, still failing, but now because the CI references the current SHA in the 1.12 DC/OS branch.  So bumping DC/OS, then bumping this, and then bumping DC/OS again... would result in a green build 😓

**Comment by tillt** [comment]
@kaysoky you can always try a custom build to validate - see https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/modules/job/DCOS_Mesos_Modules_Custom_Build/

**Comment by kaysoky** [comment]
Here's a custom build: https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/modules/job/DCOS_Mesos_Modules_Custom_Build/20/
Module `origin/pr/104/head` + Mesos `1.7.x`

**Comment by tillt** [comment]
> Here's a custom build: https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/modules/job/DCOS_Mesos_Modules_Custom_Build/20/
> Module `origin/pr/104/head` + Mesos `1.7.x`

AWESOME - all green!

**Pull request merged**
